name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: dist/storybook
          build_command: pnpm run build-storybook